name: Release

permissions:
  contents: write
  id-token: write

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '.github/workflows/semantic-release.yml'
      - '.releaserc.json'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
